leftnav:
- identifier: 1ed11da5-67c3-41f4-b966-367e508c2574
  name: About
  pageRef: /pages/about-the-inclusive-teaching-module
  weight: 10
- identifier: 7b582937-9164-4816-8f08-b79d078e3f64
  name: Online Module
  pageRef: /external-resources/online-module_7b582937-9164-4816-8f08-b79d078e3f64
  weight: 20
- identifier: 1cb50234-fa5e-4efb-a8a3-5b751bd30a9d
  name: Instructor Insights
  pageRef: /pages/instructor-insights
  weight: 30
